server:
  port: 8080

#######################################################################################################################

spring:
  # DB Connection
  datasource:
    url: jdbc:mysql://localhost:3306/pragmatic?serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
       # schema auto generate
       # ddl-auto: create
    # SQL query print
    show-sql: true
    properties:
      hibernate:
        # SQL Pretty Print
        format_sql: true
    database: mysql

#  security:
#    user:
#      name: admin
#      password: admin

  # if static resource happen change, auto apply
  devtools:
    livereload:
      enabled: true

#  thymeleaf:
#    # dont use filename with root path just use filename
#    prefix: classpath:/templates/
#    # dont use filename with .html just use filename
#    suffix: .html
#    # thymeleaf use or not
#    enabled: true
  mvc:
    view:
      suffix: .jsp
      prefix: /

# SWAGGER ERROR
# Spring boot 2.6버전 이후
# spring.mvc.pathmatch.matching-strategy => ant_apth_matcher에서 path_pattern_parser 변경
    pathmatch:
      matching-strategy: ant_path_matcher